name: Build and Deploy to NAIS

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'Dockerfile'
      - 'nginx.conf'
      - '.nais/**'
      - '.github/workflows/deploy.yaml'

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: team-researchops
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}

